// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the domain public.email */
type Email = string;

export default Email;

/** Zod schema for email */
export const email = z.unknown();
