// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.service_type */
export type ServiceTypeId = number & { __brand: 'ServiceTypeId' };

/**
 * Represents the table public.service_type
 * Service type
 */
export default interface ServiceType {
  id: ServiceTypeId;

  name: string;

  description: string;
}

/**
 * Represents the initializer for the table public.service_type
 * Service type
 */
export interface ServiceTypeInitializer {
  id?: ServiceTypeId;

  name: string;

  description: string;
}

/**
 * Represents the mutator for the table public.service_type
 * Service type
 */
export interface ServiceTypeMutator {
  id?: ServiceTypeId;

  name?: string;

  description?: string;
}

export const serviceTypeId: z.Schema<ServiceTypeId> = z.number() as any;

export const serviceType: z.Schema<ServiceType> = z.object({
  id: serviceTypeId,
  name: z.string(),
  description: z.string(),
}) as any;

export const serviceTypeInitializer: z.Schema<ServiceTypeInitializer> = z.object({
  id: serviceTypeId.optional(),
  name: z.string(),
  description: z.string(),
}) as any;

export const serviceTypeMutator: z.Schema<ServiceTypeMutator> = z.object({
  id: serviceTypeId.optional(),
  name: z.string().optional(),
  description: z.string().optional(),
}) as any;
