exports.up = async function (knex) {
  return knex.raw(`
    CREATE EXTENSION citext;
    CREATE DOMAIN email AS citext
      CHECK ( value ~ '^[a-zA-Z0-9.!#$%&''*+/=\\?^_\`{|}~-]+@[a-zA-Z0-9](\\?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])\\?(\\?:\\.[a-zA-Z0-9](\\?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])\\?)+$' );
  
    CREATE TABLE provider (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL,
      email email NOT NULL UNIQUE
    );
  `);
};

exports.down = async function (knex) {
  return knex.raw(`
    DROP TABLE provider;
    DROP DOMAIN email;
    DROP EXTENSION citext;
  `);
};
