// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from 'knex';
import type { default as ServiceType, ServiceTypeInitializer, ServiceTypeMutator } from './public/ServiceType';
import type { default as Provider, ProviderInitializer, ProviderMutator } from './public/Provider';
import type { default as Customer, CustomerInitializer, CustomerMutator } from './public/Customer';
import type { default as Booking, BookingInitializer, BookingMutator } from './public/Booking';

declare module 'knex/types/tables' {
  interface Tables {
    'service_type': Knex.CompositeTableType<ServiceType, ServiceTypeInitializer, ServiceTypeMutator>;
    'provider': Knex.CompositeTableType<Provider, ProviderInitializer, ProviderMutator>;
    'customer': Knex.CompositeTableType<Customer, CustomerInitializer, CustomerMutator>;
    'booking': Knex.CompositeTableType<Booking, BookingInitializer, BookingMutator>;
  }
}
